name: Build & Deploy Airflow
on:
  push:
    branches: [ "main" ]  # ajuste si besoin

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      # 1) Buildx pour activer le cache GHA
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: image=moby/buildkit:latest

      # 2) Construire le nom d'image en MINUSCULES
      - name: Set IMAGE env (lowercase)
        run: |
          REPO_LC=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE=ghcr.io/${REPO_LC}-airflow:prod" >> $GITHUB_ENV
          echo "Using image: $IMAGE"

      # 3) Login GHCR pour push
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4) Build & Push (avec cache GHA)
      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 5) SSH vers le VPS
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.VPS_HOST }}" >> ~/.ssh/known_hosts

      # 6) Mettre à jour l'image dans le compose et redémarrer
      - name: Pull & Restart on VPS
        env:
          IMAGE: ${{ env.IMAGE }}
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} bash -lc '
            docker login ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.GHCR_PAT }}
            # remplace l'ancienne référence par la nouvelle (toute chaîne finissant par "-airflow:prod")
            sed -i "s|ghcr.io/.\\+-airflow:prod|'"$IMAGE"'|g" /opt/airflow/docker-compose.yml
            docker compose -f /opt/airflow/docker-compose.yml pull
            docker compose -f /opt/airflow/docker-compose.yml up -d
          '
